"""Hard delete for admins: permanent removal of any record shown in the admin panel or CS console.

Two layers:

  cascades      delete_post_cascade and delete_user_cascade, and a small cascade per kind below.
                They never commit. They do NOT rely on database ON DELETE behaviour -- some foreign
                keys cascade, many don't, and they were added across several phases -- so every
                dependent row is deleted, detached or anonymised explicitly, in an order PostgreSQL
                accepts with its foreign keys enforced. (The tests run SQLite, which does not
                enforce them by default; tests/test_admin_hard_delete.py switches enforcement on.)

  the registry  KINDS maps a name ('post', 'contact_message', ...) to how to find, guard, cascade
                and log one row. hard_delete(kind, ids, actor) is the single entry point every
                delete button in both consoles goes through: one admin check, one audit format,
                one commit, files removed only after the commit succeeds.

Nothing here is reversible; callers confirm intent first (the type-DELETE dialog for anything with
dependants, a plain confirm for a leaf row).

What is deliberately NOT deletable, and why:
  Match / MatchParty   regenerated by the matcher on the next look at a post -- a deleted match
                       comes straight back. Dismiss is the removal that lasts.
  TripLeg              derived from the post and rebuilt on every save.
  ContactPoint         edited and removed on the post form already.
  ContactReply         the record of an e-mail that was actually sent; goes with its enquiry.
  Chats                private conversations between two people, shown on no staff screen.
  AppSetting           configuration, each blob with its own editor.
"""
from dataclasses import dataclass, field
from typing import Callable, Optional

from app import db


# ---------------------------------------------------------------------------
# Shared pieces
# ---------------------------------------------------------------------------

def _forget_reads(read_kind, ids):
    """Drop staff "has opened this" marks for rows that no longer exist. They point at rows by a
    plain id with no foreign key, so nothing else would ever clear them."""
    from app.models import StaffRead
    ids = [i for i in (ids or []) if i is not None]
    if ids:
        StaffRead.query.filter(StaffRead.kind == read_kind, StaffRead.item_id.in_(ids)) \
            .delete(synchronize_session=False)


def _delete_matches(match_ids):
    """Matches and everything hanging off them: reports, parties, read marks."""
    from app.models import Match, MatchParty, MatchReport
    match_ids = list(match_ids or [])
    if not match_ids:
        return
    report_ids = [r.id for r in MatchReport.query.filter(MatchReport.match_id.in_(match_ids)).all()]
    _forget_reads('report', report_ids)
    _forget_reads('match', match_ids)
    MatchReport.query.filter(MatchReport.match_id.in_(match_ids)).delete(synchronize_session=False)
    MatchParty.query.filter(MatchParty.match_id.in_(match_ids)).delete(synchronize_session=False)
    Match.query.filter(Match.id.in_(match_ids)).delete(synchronize_session=False)


def _delete_matches_for_trip_ids(trip_ids):
    """Remove every Match touching any of these posts, plus its parties and reports."""
    from app.models import Match, MatchParty, MatchReport
    trip_ids = list(trip_ids or [])
    if not trip_ids:
        return
    match_ids = [m.id for m in Match.query.filter(
        db.or_(Match.trip_a_id.in_(trip_ids), Match.trip_b_id.in_(trip_ids))).all()]
    _delete_matches(match_ids)
    # belt and braces: parties and reports are always tied to a match touching the post, but both
    # also carry trip_id, and a NOT NULL / un-cascaded trip_id left behind would block the delete
    MatchReport.query.filter(MatchReport.trip_id.in_(trip_ids)).delete(synchronize_session=False)
    MatchParty.query.filter(MatchParty.trip_id.in_(trip_ids)).delete(synchronize_session=False)


# ---------------------------------------------------------------------------
# Posts and users
# ---------------------------------------------------------------------------

def delete_post_cascade(trip, files=None):
    """Permanently delete one CompanionRequest and everything that only makes sense with it.

    `files`, when given, collects what to remove from storage AFTER the commit (a rolled-back
    delete must not have already destroyed the ticket it would have kept).

    Chats are kept and detached, not deleted: a chat room belongs to a PAIR of people and is reused
    across all their posts (ChatRoom.get_or_create), so deleting the rooms of one post wiped that
    pair's whole conversation, including what they said about other trips.
    """
    from app.models import (ContactPoint, ClaimToken, ConnectionRequest, ChatRoom,
                            ActivityEvent, TripLeg, Notification, ScrapeRow)
    trip_id = trip.id

    _delete_matches_for_trip_ids([trip_id])

    conn_ids = [c.id for c in ConnectionRequest.query.filter_by(trip_id=trip_id).all()]
    if conn_ids:
        Notification.query.filter(Notification.connection_id.in_(conn_ids)) \
            .update({'connection_id': None}, synchronize_session=False)
        ConnectionRequest.query.filter(ConnectionRequest.id.in_(conn_ids)).delete(synchronize_session=False)

    ChatRoom.query.filter_by(trip_id=trip_id).update({'trip_id': None}, synchronize_session=False)

    ContactPoint.query.filter_by(trip_id=trip_id).delete(synchronize_session=False)
    ClaimToken.query.filter_by(trip_id=trip_id).delete(synchronize_session=False)
    ActivityEvent.query.filter_by(trip_id=trip_id).delete(synchronize_session=False)
    TripLeg.query.filter_by(trip_id=trip_id).delete(synchronize_session=False)
    # a scraped row whose post is gone is third-party data with no reason to keep: mark it skipped
    # so the retention job purges it on schedule (it keeps 'imported' rows forever)
    for col in (ScrapeRow.duplicate_of_id, ScrapeRow.imported_post_id):
        ScrapeRow.query.filter(col == trip_id, ScrapeRow.status.in_(('imported', 'duplicate'))) \
            .update({'status': 'skipped'}, synchronize_session=False)
    ScrapeRow.query.filter_by(duplicate_of_id=trip_id).update({'duplicate_of_id': None}, synchronize_session=False)
    ScrapeRow.query.filter_by(imported_post_id=trip_id).update({'imported_post_id': None}, synchronize_session=False)

    if files is not None and trip.ticket_attachment:
        files.append(('private', trip.ticket_attachment))
    db.session.delete(trip)


def delete_user_cascade(user, actor=None, files=None):
    """Permanently delete a user, everything that is theirs, and anonymise their footprint in other
    people's records.

    Ordered for PostgreSQL. The old version missed several references that only PostgreSQL
    enforces (posts a CS agent created, enquiries they handled, bookings they assigned, settings
    an admin saved, notifications about their connection requests), so deleting nearly any staff
    account raised an IntegrityError in production while passing every SQLite test.

    Blog posts written by the user are REASSIGNED to the acting admin rather than deleted:
    deleting an admin used to silently wipe the public blog posts they had written.
    """
    from app.models import (CompanionRequest, Feedback, ChatRoom, ChatMessage, Notification,
                            ConnectionRequest, ContactPoint, ActivityEvent, ClaimToken,
                            MatchParty, Match, MatchReport, Blog, ContactMessage, ContactReply,
                            InsuranceQuote, SahayakBooking, SavedFilter, AppSetting, StaffRead)
    user_id = user.id

    # 1. their posts, with everything tied to them
    for trip in CompanionRequest.query.filter_by(user_id=user_id).all():
        delete_post_cascade(trip, files)
    # 2. posts they created for someone else (CS, imports) stay; the creator is forgotten
    CompanionRequest.query.filter_by(created_by_id=user_id).update({'created_by_id': None}, synchronize_session=False)
    CompanionRequest.query.filter_by(closed_by_id=user_id).update({'closed_by_id': None}, synchronize_session=False)

    # 3. connection requests they made -- notifications about them first
    conn_ids = [c.id for c in ConnectionRequest.query.filter_by(requester_id=user_id).all()]
    if conn_ids:
        Notification.query.filter(Notification.connection_id.in_(conn_ids)) \
            .update({'connection_id': None}, synchronize_session=False)
        ConnectionRequest.query.filter(ConnectionRequest.id.in_(conn_ids)).delete(synchronize_session=False)

    # 4. their chats: every room they are in, with its messages and attachments
    room_ids = [r.id for r in ChatRoom.query.filter(
        db.or_(ChatRoom.user1_id == user_id, ChatRoom.user2_id == user_id)).all()]
    if room_ids:
        if files is not None:
            for (url,) in db.session.query(ChatMessage.file_url).filter(
                    ChatMessage.room_id.in_(room_ids), ChatMessage.file_url.isnot(None)).all():
                files.append(('public', url))
        ChatMessage.query.filter(ChatMessage.room_id.in_(room_ids)).delete(synchronize_session=False)
        ChatRoom.query.filter(ChatRoom.id.in_(room_ids)).delete(synchronize_session=False)

    # 5. their own records
    Notification.query.filter_by(user_id=user_id).delete(synchronize_session=False)
    fb_ids = [f.id for f in Feedback.query.filter_by(user_id=user_id).all()]
    _forget_reads('feedback', fb_ids)
    Feedback.query.filter_by(user_id=user_id).delete(synchronize_session=False)
    ContactPoint.query.filter_by(user_id=user_id).delete(synchronize_session=False)
    SavedFilter.query.filter_by(owner_id=user_id).delete(synchronize_session=False)
    StaffRead.query.filter_by(user_id=user_id).delete(synchronize_session=False)

    # 6. the blog keeps its posts: reassigned to whoever is deleting (author_id is NOT NULL)
    if actor is not None and getattr(actor, 'id', None) and actor.id != user_id:
        Blog.query.filter_by(author_id=user_id).update({'author_id': actor.id}, synchronize_session=False)
    else:
        Blog.query.filter_by(author_id=user_id).delete(synchronize_session=False)

    # 7. what they sent us: enquiries (with replies), insurance quotes, Sahayak bookings
    msg_ids = [m.id for m in ContactMessage.query.filter_by(user_id=user_id).all()]
    if msg_ids:
        _forget_reads('contact', msg_ids)
        ContactReply.query.filter(ContactReply.message_id.in_(msg_ids)).delete(synchronize_session=False)
        ContactMessage.query.filter(ContactMessage.id.in_(msg_ids)).delete(synchronize_session=False)
    InsuranceQuote.query.filter_by(user_id=user_id).delete(synchronize_session=False)
    SahayakBooking.query.filter_by(user_id=user_id).delete(synchronize_session=False)

    # 8. their footprint in other people's records: anonymised, so that history stays intact
    for col in (ActivityEvent.actor_id, ClaimToken.created_by_id, MatchParty.sent_by_id,
                Match.cs_owner_id, MatchReport.reporter_id, MatchReport.resolved_by_id,
                ContactMessage.handled_by_id, ContactReply.author_id,
                SahayakBooking.assigned_by_id, AppSetting.updated_by_id):
        col.class_.query.filter(col == user_id).update({col.key: None}, synchronize_session=False)
    try:
        from app.models import ScrapeRow, ScrapeRecipe, ScrapeRun
        ScrapeRow.query.filter_by(imported_by_id=user_id).update({'imported_by_id': None}, synchronize_session=False)
        ScrapeRecipe.query.filter_by(created_by_id=user_id).update({'created_by_id': None}, synchronize_session=False)
        ScrapeRun.query.filter_by(started_by_id=user_id).update({'started_by_id': None}, synchronize_session=False)
    except ImportError:      # pragma: no cover - scraper models optional
        pass

    # 9. their uploaded photo (never an OAuth provider's URL)
    if files is not None and user.photo_url:
        files.append(('public', user.photo_url))
    db.session.delete(user)


# ---------------------------------------------------------------------------
# The registry
# ---------------------------------------------------------------------------

@dataclass
class Kind:
    model: Callable                     # returns the model class (imported lazily)
    noun: str                           # what one of these is called on screen
    event: str                          # the audit event, <= 40 chars
    label: Callable = lambda o: '#%s' % o.id
    tier: str = 'confirm'               # 'type' = the type-DELETE dialog; 'confirm' = a plain confirm
    guard: Optional[Callable] = None    # (obj, actor) -> error string or None
    cascade: Optional[Callable] = None  # (obj, actor, files) -> None; default: delete the row
    after: Optional[Callable] = None    # (objs) -> None, before the commit, once per batch
    meta: Callable = lambda o: {}


def _m(name):
    def get():
        from app import models
        return getattr(models, name)
    return get


def _guard_user(user, actor):
    if actor is not None and user.id == actor.id:
        return 'You cannot delete your own account.'
    return None


def _cascade_contact(msg, actor, files):
    """The replies go through the ORM, not a bulk delete: `replies` loads with the enquiry
    (selectin), and the relationship's cascade then deletes those same rows again -- a second
    delete that matches nothing and warns."""
    _forget_reads('contact', [msg.id])
    for reply in list(msg.replies):
        db.session.delete(reply)
    db.session.delete(msg)


def delete_feedback(fb, actor=None, files=None):
    """A review and the read marks on it. Public because Reject -- which any agent with the
    voices screen may do -- is this same delete, on both consoles."""
    _forget_reads('feedback', [fb.id])
    db.session.delete(fb)


def _cascade_report(report, actor, files):
    """A deleted report must not leave its match stuck in the CS queue: when it was the last open
    report on that match, the match stops needing attention -- exactly what resolving it does."""
    from app.models import Match, MatchReport
    _forget_reads('report', [report.id])
    match_id = report.match_id
    db.session.delete(report)
    db.session.flush()
    if match_id and not MatchReport.query.filter_by(match_id=match_id, status='open').count():
        m = db.session.get(Match, match_id)
        if m is not None and m.needs_cs_attention:
            m.needs_cs_attention = False


def _cascade_blog(blog, actor, files):
    """Notifications pointing at the post would open a 404."""
    from app.models import Notification
    if blog.slug:
        Notification.query.filter(Notification.link == '/blog/%s' % blog.slug) \
            .delete(synchronize_session=False)
    db.session.delete(blog)


MANUAL_EVENTS = ('note', 'dm_sent', 'called', 'claim_link_sent_manual')


def _guard_event(ev, actor):
    if ev.event not in MANUAL_EVENTS:
        return 'System events are the audit trail and cannot be deleted.'
    return None


def _guard_scrape_active(run, actor):
    if run.status in ('queued', 'running'):
        return 'That run is still going -- cancel it first.'
    return None


def _guard_recipe(recipe, actor):
    from app.models import ScrapeRun
    if ScrapeRun.query.filter(ScrapeRun.recipe_id == recipe.id,
                              ScrapeRun.status.in_(('queued', 'running'))).count():
        return 'A run of this recipe is still going -- cancel it first.'
    return None


def _cascade_run(run, actor, files):
    """Its rows first: ScrapeRun.rows has no cascade and run_id is NOT NULL. A teach run's
    saved_path is NOT removed -- it is the recipe's own saved browser session, which later runs
    still sign in with; it goes when the recipe does."""
    from app.models import ScrapeRow
    ScrapeRow.query.filter_by(run_id=run.id).delete(synchronize_session=False)
    db.session.delete(run)


def _cascade_recipe(recipe, actor, files):
    """Bulk deletes, not the ORM cascade: a big recipe's rows would all be loaded one by one."""
    from app.models import ScrapeRow, ScrapeRun, ScrapeRecipe
    if files is not None and getattr(recipe, 'session_key', None):
        others = ScrapeRecipe.query.filter(ScrapeRecipe.session_key == recipe.session_key,
                                           ScrapeRecipe.id != recipe.id).count()
        if not others:
            files.append(('scraper_session', recipe.session_key))
    ScrapeRow.query.filter_by(recipe_id=recipe.id).delete(synchronize_session=False)
    ScrapeRun.query.filter_by(recipe_id=recipe.id).delete(synchronize_session=False)
    db.session.delete(recipe)


KINDS = {
    'user': Kind(_m('User'), 'account', 'user_hard_deleted', label=lambda u: u.username or u.email,
                 tier='type', guard=_guard_user,
                 cascade=lambda u, actor, files: delete_user_cascade(u, actor, files),
                 meta=lambda u: {'target_user_id': u.id, 'username': u.username}),
    'post': Kind(_m('CompanionRequest'), 'post', 'post_hard_deleted', label=lambda t: 'post #%s' % t.id,
                 tier='type', cascade=lambda t, actor, files: delete_post_cascade(t, files),
                 meta=lambda t: {'target_trip_id': t.id, 'route': t.route_display}),
    'contact_message': Kind(_m('ContactMessage'), 'enquiry', 'contact_hard_deleted',
                            label=lambda m: '%s <%s>' % (m.name, m.email), tier='type',
                            cascade=_cascade_contact,
                            meta=lambda m: {'contact_id': m.id, 'email': m.email, 'topic': m.topic}),
    'insurance_quote': Kind(_m('InsuranceQuote'), 'insurance quote request', 'insurance_quote_hard_deleted',
                            label=lambda q: q.email,
                            meta=lambda q: {'quote_id': q.id, 'email': q.email}),
    'sahayak_booking': Kind(_m('SahayakBooking'), 'Sahayak booking', 'sahayak_booking_hard_deleted',
                            label=lambda b: '%s for %s' % (b.service_name, b.patient_name),
                            meta=lambda b: {'booking_id': b.id, 'service': b.service_key}),
    'blog': Kind(_m('Blog'), 'blog post', 'blog_hard_deleted', label=lambda b: b.title, tier='type',
                 cascade=_cascade_blog, meta=lambda b: {'blog_id': b.id, 'slug': b.slug}),
    'match_report': Kind(_m('MatchReport'), 'match report', 'match_report_hard_deleted',
                         cascade=_cascade_report, meta=lambda r: {'report_id': r.id, 'match_id': r.match_id}),
    'notification': Kind(_m('Notification'), 'notification', 'notification_hard_deleted',
                         meta=lambda n: {'notification_id': n.id, 'user_id': n.user_id}),
    'feedback': Kind(_m('Feedback'), 'review', 'feedback_hard_deleted', cascade=delete_feedback,
                     meta=lambda f: {'feedback_id': f.id, 'site': getattr(f, 'site', None)}),
    'saved_filter': Kind(_m('SavedFilter'), 'saved view', 'saved_filter_hard_deleted',
                         label=lambda s: s.name, meta=lambda s: {'filter_id': s.id, 'owner_id': s.owner_id}),
    'claim_token': Kind(_m('ClaimToken'), 'claim link', 'claim_link_revoked',
                        meta=lambda c: {'token_id': c.id, 'trip_id': c.trip_id}),
    'activity_event': Kind(_m('ActivityEvent'), 'activity entry', 'activity_entry_deleted',
                           guard=_guard_event, meta=lambda e: {'event_id': e.id, 'was': e.event,
                                                                'trip_id': e.trip_id}),
    'scrape_recipe': Kind(_m('ScrapeRecipe'), 'scraper recipe', 'scrape_recipe_deleted',
                          label=lambda r: r.name, tier='type', guard=_guard_recipe,
                          cascade=_cascade_recipe, meta=lambda r: {'recipe_id': r.id, 'name': r.name}),
    'scrape_run': Kind(_m('ScrapeRun'), 'scraper run', 'scrape_run_deleted', tier='type',
                       guard=_guard_scrape_active, cascade=_cascade_run,
                       meta=lambda r: {'run_id': r.id, 'recipe_id': r.recipe_id}),
    'scrape_row': Kind(_m('ScrapeRow'), 'scraped row', 'scrape_row_deleted',
                       meta=lambda r: {'row_id': r.id, 'run_id': r.run_id}),
}


def remove_files(files):
    """Delete stored files for rows already gone. Called only after a successful commit."""
    from flask import current_app
    from app.services import storage
    for where, ref in files or []:
        try:
            if where == 'private':
                storage.delete_private(ref)
            elif where == 'public':
                storage.delete_public(ref)
            elif where == 'scraper_session':
                storage.delete_scraper_session(ref)
        except Exception:                     # noqa: BLE001 -- the rows are already gone
            current_app.logger.exception('Could not remove %s file %r after a delete', where, ref)


SCRAPER_KINDS = ('scrape_recipe', 'scrape_run', 'scrape_row')


def available(kind):
    """Whether `kind` can be deleted on this deployment: the scraper's kinds go away with the
    scraper (SCRAPER_ENABLED=0), the same way its screens answer 404."""
    from flask import current_app
    if kind not in KINDS:
        return False
    if kind in SCRAPER_KINDS and not current_app.config.get('SCRAPER_ENABLED', True):
        return False
    return True


def hard_delete(kind, ids, actor):
    """Permanently delete rows of one kind. Returns {'deleted': [ids], 'skipped': [{'id', 'error'}]}.

    One commit for the whole batch; files are removed only after it succeeds. Every deleted row
    is logged as '<kind>_hard_deleted' (or the kind's own event) with no trip=, so the audit entry
    outlives the post it describes.
    """
    from app.models import ActivityEvent
    spec = KINDS.get(kind)
    if spec is None:
        raise KeyError(kind)
    model = spec.model()
    clean = sorted({int(i) for i in (ids or []) if isinstance(i, int) or str(i).isdigit()})
    rows = model.query.filter(model.id.in_(clean)).all() if clean else []
    found = {r.id for r in rows}
    skipped = [{'id': i, 'error': 'Not found -- it may already have been deleted.'}
               for i in clean if i not in found]
    deleted, files = [], []
    for obj in rows:
        why = spec.guard(obj, actor) if spec.guard else None
        if why:
            skipped.append({'id': obj.id, 'error': why})
            continue
        meta = dict(spec.meta(obj) or {})
        meta['label'] = str(spec.label(obj))[:120]
        ActivityEvent.log(spec.event, actor=actor, **meta)
        if spec.cascade:
            spec.cascade(obj, actor, files)
        else:
            db.session.delete(obj)
        deleted.append(obj.id)
    db.session.commit()
    remove_files(files)
    return {'deleted': deleted, 'skipped': skipped}
