"""phase 3: scraper recipes, runs, rows

Revision ID: 197f9c09b7d7
Revises: 42c5ee51a155
Create Date: 2026-08-30 03:35:07.285854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '197f9c09b7d7'
down_revision = '42c5ee51a155'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scrape_recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('site', sa.String(length=200), nullable=True),
    sa.Column('start_url', sa.String(length=500), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=True),
    sa.Column('recipe_json', sa.JSON(), nullable=True),
    sa.Column('source_json', sa.JSON(), nullable=True),
    sa.Column('field_mapping', sa.JSON(), nullable=True),
    sa.Column('default_source', sa.String(length=20), nullable=True),
    sa.Column('session_key', sa.String(length=300), nullable=True),
    sa.Column('schedule_enabled', sa.Boolean(), nullable=True),
    sa.Column('schedule_every_hours', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_status', sa.String(length=15), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('scrape_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=True),
    sa.Column('trigger', sa.String(length=10), nullable=True),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=True),
    sa.Column('log', sa.Text(), nullable=True),
    sa.Column('progress_pages', sa.Integer(), nullable=True),
    sa.Column('progress_items', sa.Integer(), nullable=True),
    sa.Column('rows_total', sa.Integer(), nullable=True),
    sa.Column('rows_new', sa.Integer(), nullable=True),
    sa.Column('rows_duplicate', sa.Integer(), nullable=True),
    sa.Column('cancel_requested', sa.Boolean(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('worker_id', sa.String(length=64), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(), nullable=True),
    sa.Column('started_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['scrape_recipes.id'], ),
    sa.ForeignKeyConstraint(['started_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scrape_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scrape_runs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_scrape_runs_recipe_id'), ['recipe_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scrape_runs_status'), ['status'], unique=False)

    # A recipe may have at most one queued/running run at a time, even across gunicorn workers.
    op.create_index('uq_scrape_runs_active', 'scrape_runs', ['recipe_id'], unique=True,
                    postgresql_where=sa.text("status IN ('queued','running')"),
                    sqlite_where=sa.text("status IN ('queued','running')"))

    op.create_table('scrape_rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('page_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=True),
    sa.Column('duplicate_of_id', sa.Integer(), nullable=True),
    sa.Column('imported_post_id', sa.Integer(), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=True),
    sa.Column('imported_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['companion_requests.id'], ),
    sa.ForeignKeyConstraint(['imported_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['imported_post_id'], ['companion_requests.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['scrape_recipes.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['scrape_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recipe_id', 'key', name='uq_scrape_rows_recipe_key')
    )
    with op.batch_alter_table('scrape_rows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scrape_rows_key'), ['key'], unique=False)
        batch_op.create_index(batch_op.f('ix_scrape_rows_recipe_id'), ['recipe_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scrape_rows_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scrape_rows_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scrape_rows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scrape_rows_status'))
        batch_op.drop_index(batch_op.f('ix_scrape_rows_run_id'))
        batch_op.drop_index(batch_op.f('ix_scrape_rows_recipe_id'))
        batch_op.drop_index(batch_op.f('ix_scrape_rows_key'))

    op.drop_table('scrape_rows')
    with op.batch_alter_table('scrape_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scrape_runs_status'))
        batch_op.drop_index(batch_op.f('ix_scrape_runs_recipe_id'))
        batch_op.drop_index(batch_op.f('ix_scrape_runs_created_at'))

    op.drop_index('uq_scrape_runs_active', table_name='scrape_runs')
    op.drop_table('scrape_runs')
    op.drop_table('scrape_recipes')
    # ### end Alembic commands ###
