"""user roles list

Revision ID: 21b69192e4b0
Revises: 712b4e698438
Create Date: 2026-08-31 00:26:32.277692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21b69192e4b0'
down_revision = '712b4e698438'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roles', sa.JSON(), nullable=True))

    # ### end Alembic commands ###

    # Backfill: every existing account gets its legacy single role (+ admin) as a roles list.
    conn = op.get_bind()
    users = sa.table('users', sa.column('id', sa.Integer), sa.column('role', sa.String),
                     sa.column('is_admin', sa.Boolean), sa.column('roles', sa.JSON))
    for id_, role, is_admin in conn.execute(sa.select(users.c.id, users.c.role, users.c.is_admin)).fetchall():
        keys = [role or 'user']
        if is_admin and 'admin' not in keys:
            keys.append('admin')
        conn.execute(users.update().where(users.c.id == id_).values(roles=keys))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('roles')

    # ### end Alembic commands ###
