"""phase 2b: matches and match parties

Revision ID: 27e9d0a669ee
Revises: 262b3294a429
Create Date: 2026-08-29 23:59:48.156697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27e9d0a669ee'
down_revision = '262b3294a429'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_a_id', sa.Integer(), nullable=False),
    sa.Column('trip_b_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('criteria', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=True),
    sa.Column('dismissed_reason', sa.String(length=40), nullable=True),
    sa.Column('cs_owner_id', sa.Integer(), nullable=True),
    sa.Column('needs_cs_attention', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cs_owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['trip_a_id'], ['companion_requests.id'], ),
    sa.ForeignKeyConstraint(['trip_b_id'], ['companion_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_a_id', 'trip_b_id', name='uq_matches_pair')
    )
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matches_needs_cs_attention'), ['needs_cs_attention'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_trip_a_id'), ['trip_a_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_trip_b_id'), ['trip_b_id'], unique=False)

    op.create_table('match_parties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=True),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('sent_by_id', sa.Integer(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('viewed_at', sa.DateTime(), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['sent_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['companion_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'trip_id', name='uq_match_parties_side')
    )
    with op.batch_alter_table('match_parties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_parties_match_id'), ['match_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_parties_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_parties_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_match_parties_trip_id'), ['trip_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_parties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_parties_trip_id'))
        batch_op.drop_index(batch_op.f('ix_match_parties_token'))
        batch_op.drop_index(batch_op.f('ix_match_parties_status'))
        batch_op.drop_index(batch_op.f('ix_match_parties_match_id'))

    op.drop_table('match_parties')
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matches_trip_b_id'))
        batch_op.drop_index(batch_op.f('ix_matches_trip_a_id'))
        batch_op.drop_index(batch_op.f('ix_matches_status'))
        batch_op.drop_index(batch_op.f('ix_matches_needs_cs_attention'))

    op.drop_table('matches')
    # ### end Alembic commands ###
