"""phase 2c: escalation and alert throttle columns

Revision ID: 42c5ee51a155
Revises: 27e9d0a669ee
Create Date: 2026-08-30 00:26:04.990029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42c5ee51a155'
down_revision = '27e9d0a669ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companion_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_match_alert_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('match_parties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('escalated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_parties', schema=None) as batch_op:
        batch_op.drop_column('escalated_at')

    with op.batch_alter_table('companion_requests', schema=None) as batch_op:
        batch_op.drop_column('last_match_alert_at')

    # ### end Alembic commands ###
