"""add connection_requests

Revision ID: 62148d13d6ed
Revises: d159a559aaac
Create Date: 2026-05-22 14:15:04.498897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62148d13d6ed'
down_revision = 'd159a559aaac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connection_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('requester_anonymous', sa.Boolean(), nullable=True),
    sa.Column('recipient_anonymous', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['companion_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('connection_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_notifications_connection_id', 'connection_requests', ['connection_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint('fk_notifications_connection_id', type_='foreignkey')
        batch_op.drop_column('connection_id')

    op.drop_table('connection_requests')
    # ### end Alembic commands ###
