"""airlines table

Revision ID: 6389d25b1557
Revises: 39cd7630a97b
Create Date: 2026-08-31 01:10:19.999474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6389d25b1557'
down_revision = '39cd7630a97b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airlines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iata', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('country', sa.String(length=80), nullable=True),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('airlines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_airlines_iata'), ['iata'], unique=True)

    # ### end Alembic commands ###

    # Seed from the bundled airline list (app/static/js/airlines.json)
    import json
    import os
    conn = op.get_bind()
    if not conn.execute(sa.text("SELECT COUNT(*) FROM airlines")).scalar():
        root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
        with open(os.path.join(root, 'app', 'static', 'js', 'airlines.json'), encoding='utf-8') as f:
            data = json.load(f)
        airlines = sa.table('airlines', sa.column('iata', sa.String), sa.column('name', sa.String),
                            sa.column('country', sa.String), sa.column('is_custom', sa.Boolean))
        seen, rows = set(), []
        for a in data:
            iata = (a.get('iata') or '').strip().upper()
            if not iata or iata in seen:
                continue
            seen.add(iata)
            rows.append({'iata': iata, 'name': (a.get('name') or iata)[:150],
                         'country': (a.get('country') or '')[:80], 'is_custom': False})
        op.bulk_insert(airlines, rows)
        # Airlines admins added under the old app_settings mechanism become custom rows
        row = conn.execute(sa.text("SELECT value FROM app_settings WHERE \"key\" = 'options'")).fetchone()
        if row and row[0]:
            value = json.loads(row[0]) if isinstance(row[0], str) else dict(row[0])
            extras = value.pop('airlines', None) or []
            for a in extras:
                iata = (a.get('iata') or '').strip().upper()
                if iata and iata not in seen:
                    seen.add(iata)
                    op.bulk_insert(airlines, [{'iata': iata, 'name': a.get('name') or iata,
                                               'country': a.get('country') or '', 'is_custom': True}])
            if extras is not None:
                conn.execute(sa.text("UPDATE app_settings SET value = :v WHERE \"key\" = 'options'")
                             .bindparams(v=json.dumps(value)))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('airlines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_airlines_iata'))

    op.drop_table('airlines')
    # ### end Alembic commands ###
