"""notification switches: app_settings and user notify_prefs

Revision ID: 712b4e698438
Revises: 197f9c09b7d7
Create Date: 2026-08-30 23:41:06.991758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '712b4e698438'
down_revision = '197f9c09b7d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notify_prefs', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('notify_prefs')

    op.drop_table('app_settings')
    # ### end Alembic commands ###
