"""add additional_comments

Revision ID: d159a559aaac
Revises: 1bff17cfbcf8
Create Date: 2026-05-22 13:37:57.215868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd159a559aaac'
down_revision = '1bff17cfbcf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companion_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('additional_comments', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companion_requests', schema=None) as batch_op:
        batch_op.drop_column('additional_comments')

    # ### end Alembic commands ###
