"""Saved filters for the post listings.

One table. The autogenerated draft also wanted to drop and recreate the insurance_quotes
user_id foreign key -- that is Alembic failing to see the existing ON DELETE SET NULL, not a
real change, and re-creating it would quietly drop that clause. Removed.

Revision ID: i1sav001
Revises: h1sah001
Create Date: 2026-09-26
"""
import sqlalchemy as sa
from alembic import op

revision = 'i1sav001'
down_revision = 'h1sah001'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        'saved_filters',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('owner_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=60), nullable=False),
        # the filter engine's own params; JSON so adding a filter needs no migration here
        sa.Column('params', sa.JSON(), nullable=False),
        sa.Column('sort', sa.String(length=20), nullable=True),
        sa.Column('shared', sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column('position', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('last_used_at', sa.DateTime(), nullable=True),
        sa.Column('use_count', sa.Integer(), nullable=False, server_default='0'),
        sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('owner_id', 'name', name='uq_saved_filter_owner_name'),
    )
    op.create_index('ix_saved_filters_owner_id', 'saved_filters', ['owner_id'])
    op.create_index('ix_saved_filters_shared', 'saved_filters', ['shared'])


def downgrade():
    op.drop_index('ix_saved_filters_shared', table_name='saved_filters')
    op.drop_index('ix_saved_filters_owner_id', table_name='saved_filters')
    op.drop_table('saved_filters')
